# Generated by Django 5.2.8 on 2025-11-21 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='SensorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(help_text='External Sensor ID', max_length=100)),
                ('sensor_type', models.CharField(choices=[('TEMPERATURE', 'Temperature'), ('VIBRATION', 'Vibration'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_tags', to='assets.asset')),
            ],
        ),
    ]
