# Generated by Django 5.2.8 on 2025-11-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='asset',
            name='library_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='library.asset3d'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='position_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='position_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='rotation_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='rotation_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='rotation_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='scale_x',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='scale_y',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='scale_z',
            field=models.FloatField(default=1.0),
        ),
    ]
