# Generated by Django 5.2.8 on 2025-11-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_configuration_asset_library_asset_asset_parent_and_more'),
        ('devices', '0002_device_latest_telemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bound_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_assets', to='devices.device'),
        ),
        migrations.AddField(
            model_name='asset',
            name='telemetry_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Map 3D props to telemetry keys. e.g. {'rotation_y': 'rpm'}"),
        ),
    ]
