# Generated by Django 5.2.8 on 2025-11-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latest_telemetry',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
